version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: auntification
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        JWT_SECRET_KEY: ${JWT_SECRET_KEY:-default_dev_key}
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=123456789
      - DB_NAME=auntification
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ["go", "run", "main.go"]

volumes:
  pgdata: